In [1]:
"""
v0.1 stock valuation

this program is intended to be split into 2-3 parts

the first part is finding the stock's value to me. specifically by figuring out the roi on 
dividends of the companies that have had increasing dividends for a certain amount of time
"""

"\nv0.1 stock valuation\n\nthis program is intended to be split into 2-3 parts\n\nthe first part is finding the stock's value to me. specifically by figuring out the roi on \ndividends of the companies that have had increasing dividends for a certain amount of time\n"

In [2]:
import yfinance as yf

In [8]:
stock = yf.Ticker("msft")

In [9]:
stock.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.06,0.06,0.06,0.06,1031788800,0.0,0.0
1986-03-14,0.06,0.07,0.06,0.06,308160000,0.0,0.0
1986-03-17,0.06,0.07,0.06,0.07,133171200,0.0,0.0
1986-03-18,0.07,0.07,0.06,0.06,67766400,0.0,0.0
1986-03-19,0.06,0.06,0.06,0.06,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2020-06-15,184.58,190.82,184.01,188.94,32770200,0.0,0.0
2020-06-16,192.89,195.58,191.46,193.57,42556700,0.0,0.0
2020-06-17,195.03,196.32,193.69,194.24,25655900,0.0,0.0
2020-06-18,194.00,196.49,194.00,196.32,23061600,0.0,0.0
2020-06-19,198.59,199.29,194.37,195.15,44423500,0.0,0.0

In [10]:
stock.actions

            Dividends  Stock Splits
Date
1987-09-21       0.00           2.0
1990-04-16       0.00           2.0
1991-06-27       0.00           1.5
1992-06-15       0.00           1.5
1994-05-23       0.00           2.0
...               ...           ...
2019-05-15       0.46           0.0
2019-08-14       0.46           0.0
2019-11-20       0.51           0.0
2020-02-19       0.51           0.0
2020-05-20       0.51           0.0

[75 rows x 2 columns]

In [11]:
stock.dividends

Date
2003-02-19    0.08
2003-10-15    0.16
2004-08-23    0.08
2004-11-15    3.08
2005-02-15    0.08
              ...
2019-05-15    0.46
2019-08-14    0.46
2019-11-20    0.51
2020-02-19    0.51
2020-05-20    0.51
Name: Dividends, Length: 66, dtype: float64

In [12]:
stock.major_holders

        0                                      1
0   1.42%        % of Shares Held by All Insider
1  74.09%       % of Shares Held by Institutions
2  75.16%        % of Float Held by Institutions
3    4630  Number of Institutions Holding Shares

In [13]:
stock.info

{'zip': '98052',
 'sector': 'Technology',
 'fullTimeEmployees': 144000,
 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, and OneDrive; LinkedIn that includes Talent and marketing solutions, and subscriptions; and Dynamics 365, a set of cloud-based and on-premises business solutions for small and medium businesses, large organizations, and divisions of enterprises. Its Intelligent Cloud segment licenses SQL and Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also provides support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification to developers and IT professionals on various Microsoft products. Its More Personal Computing segment offers Windows OEM licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also provides Microsoft Surface, PC accessories, and other intelligent devices; Gaming, including Xbox hardware, and Xbox software and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through distributors and resellers; and directly through digital marketplaces, online stores, and retail stores. It has strategic partnerships with Humana Inc., Nokia, Telkomsel, Swiss Re, Kubota Corporation, and FedEx Corp. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'city': 'Redmond',
 'phone': '425-882-8080',
 'state': 'WA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.microsoft.com',
 'maxAge': 1,
 'address1': 'One Microsoft Way',
 'fax': '425-706-7329',
 'industry': 'Softwareâ€”Infrastructure',
 'previousClose': 196.32,
 'regularMarketOpen': 198.59,
 'twoHundredDayAverage': 169.13782,
 'trailingAnnualDividendYield': 0.010136511,
 'payoutRatio': 0.32330000000000003,
 'volume24Hr': None,
 'regularMarketDayHigh': 199.29,
 'navPrice': None,
 'averageDailyVolume10Day': 37809757,
 'totalAssets': None,
 'regularMarketPreviousClose': 196.32,
 'fiftyDayAverage': 185.66853,
 'trailingAnnualDividendRate': 1.99,
 'open': 198.59,
 'toCurrency': None,
 'averageVolume10days': 37809757,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': 2.04,
 'exDividendDate': 1597795200,
 'beta': 0.9255369999999999,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 194.37,
 'priceHint': 2,
 'currency': 'USD',
 'trailingPE': 32.51416,
 'regularMarketVolume': 44441141,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 1479908261888,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 42769184,
 'priceToSalesTrailing12Months': 10.669928,
 'dayLow': 194.37,
 'ask': 194.83,
 'ytdReturn': None,
 'askSize': 1100,
 'volume': 44441141,
 'fiftyTwoWeekHigh': 199.29,
 'forwardPE': 31.374598,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 1.92,
 'fiftyTwoWeekLow': 130.78,
 'bid': 194.6,
 'tradeable': False,
 'dividendYield': 0.010400000000000001,
 'bidSize': 900,
 'dayHigh': 199.29,
 'exchange': 'NMS',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'messageBoardId': 'finmb_21835',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 10.283,
 'beta3Year': None,
 'profitMargins': 0.33356997,
 'enterpriseToEbitda': 22.254,
 '52WeekChange': 0.4163884,
 'morningStarRiskRating': None,
 'forwardEps': 6.22,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 7583439872,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'bookValue': 15.086,
 'sharesShort': 40829581,
 'sharesPercentSharesOut': 0.0054,
 'fundFamily': None,
 'lastFiscalYearEnd': 1561852800,
 'heldPercentInstitutions': 0.7409300000000001,
 'netIncomeToCommon': 46265999360,
 'trailingEps': 6.002,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.051739097000000005,
 'priceToBook': 12.935834,
 'heldPercentInsiders': 0.014249999000000001,
 'nextFiscalYearEnd': 1625011200,
 'mostRecentQuarter': 1585612800,
 'shortRatio': 1.13,
 'sharesShortPreviousMonthDate': 1588204800,
 'floatShares': 7472267013,
 'enterpriseValue': 1426291425280,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1045526400,
 'lastSplitFactor': '2:1',
 'legalType': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.221,
 'dateShortInterest': 1590710400,
 'pegRatio': 2.27,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0055000000000000005,
 'sharesShortPriorMonth': 47763253,
 'category': None,
 'fiveYearAverageReturn': None,
 'regularMarketPrice': 198.59,
 'logo_url': 'https://logo.clearbit.com/microsoft.com'}

In [15]:
stock.balance_sheet

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [17]:
stock.cashflow

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []